### ISSUE TITLE
Папки

### ISSUE THREAD

**Issue by talgautb** [frontendkz/svg-logos#1]
Как насчет создать папки по отраслям/деятельности ?

**Comment by drugoi** [comment]
+1
Нужна структура.

**Comment by jarjan** [comment]
создал базовую структуру из того что есть, предлагайте свое и перемещайте
- **air** (аэрокомпании)
- **bank** (банк и финансы)
- **edu** (университеты и прочее)
- **government** (правительственные организации)
- **sport** (спортивные команды и прочее)
- **telecom** (операторы сотовой связи и прочие телекомы)

**Comment by jarjan** [comment]
добавлена папка **city** для лого городов

**Comment by manar-mk** [comment]
предлагаю поделить папки как на сайте [brandsoftheworld](https://www.brandsoftheworld.com/logos/categories)
Как вам такая идея?

**Comment by talgautb** [comment]
по сути, любая система подойдёт. давай просто объединять по brandsoftheworld и направлениям: города (их лого) и т.д.
дальше поймём что делать ;)
