### ISSUE TITLE
Bug: Deploy is not working

### ISSUE THREAD

**Issue by sergiozeppo** [frontendkz/svg-logos#21]
Hey there!
Noticed that demo deploy of the project is not working. 
![image](https://github.com/user-attachments/assets/361c2d34-af81-450b-a3b1-f8a6e0f04826)

I can fix that, if you don't mind.
And therefore some of the svgs, added in PRs earlier, didn't updated yet. 

I will prepare PR for fixing it. 
Take a look, please.

**Comment by jarjan** [comment]
Thanks @sergiozeppo, it is fixed!
