### ISSUE TITLE
Demopage

### ISSUE THREAD

**Issue by drugoi** [frontendkz/svg-logos#5]
Думаю, нужно демо со всеми логотипами + (возможно) поиском по ним.

**Comment by talgautb** [comment]
@manar-mk may be something like this http://svgporn.com/

**Comment by talgautb** [comment]
about https://github.com/frontendkz/svg-logos/blob/gh-pages/logos.json
@roose can you write script to auto generate json with python ?

**Comment by talgautb** [comment]
may be some template for http://frontendkz.github.io/svg-logos/ ?

**Comment by roose** [comment]
@talgautb hmm, i just deleted it =) ok, in which branch put it?

**Comment by talgautb** [comment]
@roose `gh-pages` i think

**Comment by roose** [comment]
@talgautb python script added

**Comment by talgautb** [comment]
@roose may be some instruction about script in Readme.md ?)

**Comment by roose** [comment]
@talgautb what the instructions? How to use script? =) Just run it in `gh-page` branch root folder.

**Comment by roose** [comment]
@manar-mk Incorrect json url `https://frontendkz.github.io/logos.json`
![изображение](https://user-images.githubusercontent.com/277651/94909553-2887f800-04c5-11eb-8aa5-1ca5b7481691.png)

**Comment by talgautb** [comment]
@roose why are you accepted PR ?)

**Comment by roose** [comment]
@talgautb I trusted him! And didn't notice that there are relative paths =)

**Comment by roose** [comment]
Thanks to @manar-mk 🎆
