### ISSUE TITLE
How about add json file...

### ISSUE THREAD

**Issue by roose** [frontendkz/svg-logos#8]
e.g.

``` json
[                        
  {                      
    "cat": "cities",     
    "name": "aktau.svg"  
  },                     
  {                      
    "cat": "cities",     
    "name": "almaty.svg" 
  },                     
  {                      
    "cat": "cities",     
    "name": "astana.svg" 
  }
]
```

it's will help to make search in demo page(and may be other use, e.g. in Alfred, Wox etc), I made small python script which generates json with structure above, and I can make PR if it's necessary.

**Comment by manar-mk** [comment]
@roose check my pull-request. Already did that

**Comment by roose** [comment]
@manar-mk hmm, I see only sorted files by folder, it's good, but I suggest add all logos to `logos.json` file for easily search needed logo. Because if someone wants make demo and search page I think it will be difficult to search for the current repository state, search by json much easier to implement. Gist with all logos https://gist.github.com/roose/6b81dc42b69be16257b11951e4cc7a20

Sorry for my clean english xD

**Comment by roose** [comment]
oh sorry, I see, it's in gh-page branch =)
